/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/furniture/bed_version_03.glb --types 
Author: Misam Ali Rizvi (https://sketchfab.com/MisamAliRizvi)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/bed-version-03-421fbe7bfb0944e99f4954cfd7c10bbf
Title: Bed Version 03
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Pillow_06_Black_0: THREE.Mesh
    Pillow_05_Black_0: THREE.Mesh
    Pillow_04_Black_0: THREE.Mesh
    Pillow_03_Grey_0: THREE.Mesh
    Pillow_02_Grey_0: THREE.Mesh
    Pillow_01_Foto_0: THREE.Mesh
    Bed_Part_10_Wood_0: THREE.Mesh
    Bed_Part_09_Wood_0: THREE.Mesh
    Bed_Part_08_Wood_0: THREE.Mesh
    Bed_Part_07_Wood_0: THREE.Mesh
    Bed_Part_06_Wood_0: THREE.Mesh
    Bed_Part_06_Wood_0_1: THREE.Mesh
    Bed_Part_06_Wood_0_2: THREE.Mesh
    Bed_Part_05_Offwhite_0: THREE.Mesh
    Bed_Part_04_Offwhite_0: THREE.Mesh
    Bed_Part_03_White_0: THREE.Mesh
    Bed_Part_02_Grey_0: THREE.Mesh
    Bed_Part_01_Black_0: THREE.Mesh
  }
  materials: {
    Black: THREE.MeshStandardMaterial
    Grey: THREE.MeshStandardMaterial
    Foto: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    Offwhite: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/bed_version_03.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Pillow_06_Black_0.geometry} material={materials.Black} position={[62.538, 82.494, 107.335]} />
          <group position={[-0.269, 82.51, 109.022]}>
            <mesh geometry={nodes.Pillow_05_Black_0.geometry} material={materials.Black} position={[133.554, -44.586, -47.481]} />
          </group>
          <group position={[-62.625, 82.487, 107.295]}>
            <mesh geometry={nodes.Pillow_04_Black_0.geometry} material={materials.Black} position={[195.91, -44.563, -45.754]} />
          </group>
          <group position={[-34.929, 54.829, 106.285]}>
            <mesh geometry={nodes.Pillow_03_Grey_0.geometry} material={materials.Grey} position={[168.214, -16.905, -44.744]} />
          </group>
          <group position={[34.86, 55.018, 106.306]}>
            <mesh geometry={nodes.Pillow_02_Grey_0.geometry} material={materials.Grey} position={[98.424, -17.094, -44.765]} />
          </group>
          <group position={[-6.837, 29.353, 103.252]}>
            <mesh geometry={nodes.Pillow_01_Foto_0.geometry} material={materials.Foto} position={[140.121, 8.571, -41.711]} />
          </group>
          <mesh geometry={nodes.Bed_Part_10_Wood_0.geometry} material={materials.Wood} position={[104.586, 0, 19.625]} />
          <mesh geometry={nodes.Bed_Part_07_Wood_0.geometry} material={materials.Wood} position={[0, -109.805, 19.625]} />
          <group position={[0, 0, 78.002]}>
            <mesh geometry={nodes.Bed_Part_06_Wood_0.geometry} material={materials.Wood} />
            <mesh geometry={nodes.Bed_Part_06_Wood_0_1.geometry} material={materials.Wood} />
            <mesh geometry={nodes.Bed_Part_06_Wood_0_2.geometry} material={materials.Wood} />
          </group>
          <group position={[0, 103.283, 95.947]}>
            <mesh geometry={nodes.Bed_Part_05_Offwhite_0.geometry} material={materials.Offwhite} position={[0, 0, 0.175]} />
          </group>
          <mesh geometry={nodes.Bed_Part_04_Offwhite_0.geometry} material={materials.Offwhite} position={[0, 0.022, 32.878]} />
          <group position={[-0.001, 67.632, 61.513]}>
            <mesh geometry={nodes.Bed_Part_03_White_0.geometry} material={materials.White} position={[133.286, -29.708, 0.028]} />
          </group>
          <group position={[0.692, 9.877, 64.032]}>
            <mesh geometry={nodes.Bed_Part_02_Grey_0.geometry} material={materials.Grey} position={[-0.466, 0, 0]} />
          </group>
          <group position={[0.032, -57.911, 61.522]}>
            <mesh geometry={nodes.Bed_Part_01_Black_0.geometry} material={materials.Black} position={[-0.162, -0.04, 0.129]} />
          </group>
          <mesh geometry={nodes.Bed_Part_09_Wood_0.geometry} material={materials.Wood} position={[0, 109.805, 19.625]} />
          <mesh geometry={nodes.Bed_Part_08_Wood_0.geometry} material={materials.Wood} position={[-104.586, 0, 19.625]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bed_version_03.glb')
