/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/furniture/curved_chair.glb 
Author: riach (https://sketchfab.com/riach)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/curved-chair-50cff08a315640499b06bc3a9eea6091
Title: Curved Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/curved_chair.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.008}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['curved_chair_Material_#46_0'].geometry} material={materials.Material_46} position={[0, 101.634, -27.979]} rotation={[-0.147, 0, -Math.PI]} scale={[0.845, 0.687, 0.793]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/curved_chair.glb')
