/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/DeskModel.gltf --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube007: THREE.Mesh
    Cube007_1: THREE.Mesh
  }
  materials: {
    MetalBlack: THREE.MeshStandardMaterial
    DeskWood: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/DeskModel.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-4.263, 31.74, -0.172]} scale={1.434}>
        <mesh geometry={nodes.Cube007.geometry} material={materials.MetalBlack} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials.DeskWood} />
      </group>
    </group>
  )
}

useGLTF.preload('/DeskModel.gltf')
