/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/furniture/eletric_desk.glb 
Author: Infectus (https://sketchfab.com/Infectus)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/eletric-desk-65833f64a17b4506b6e3c810df27a876
Title: Eletric Desk
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/eletric_desk.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-164.83, 68.082, -15.949]} rotation={[-Math.PI / 2, 0, 0]} scale={[4.948, 5.354, 38.94]}>
          <mesh geometry={nodes.LowerLegR_Meta_Treated_Aluminium_0.geometry} material={materials.Meta_Treated_Aluminium} />
          <mesh geometry={nodes.FeetR_Metal_Treated_0.geometry} material={materials.Metal_Treated} position={[0.013, -0.054, -1.034]} scale={[1.063, 7.869, 0.046]} />
        </group>
        <group position={[163.423, 68.082, -15.949]} rotation={[-Math.PI / 2, 0, 0]} scale={[4.948, 5.354, 38.94]}>
          <mesh geometry={nodes.LowerLegL_Meta_Treated_Aluminium_0.geometry} material={materials.Meta_Treated_Aluminium} />
          <mesh geometry={nodes.FeetL_Metal_Treated_0.geometry} material={materials.Metal_Treated} position={[0.013, -0.054, -1.034]} scale={[1.063, 7.869, 0.046]} />
        </group>
        <mesh geometry={nodes.TopDesk_Veneer_0.geometry} material={materials.Veneer} position={[-1.477, 149.544, -16.755]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.618, 149.264, 100]} />
        <mesh geometry={nodes.TableStructure_Meta_Treated_Aluminium_0.geometry} material={materials.Meta_Treated_Aluminium} position={[163.272, 103.48, -15.83]} rotation={[-Math.PI / 2, 0, 0]} scale={[4.664, 5.037, 36.482]} />
      </group>
    </group>
  )
}

useGLTF.preload('/eletric_desk.glb')
