/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/floorplan.glb --types 
Author: Baezeni (https://sketchfab.com/baezeni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-premium-floorplan-c10-a2475c32d03949479b7f68dd03a9f851
Title: 3D Premium Floorplan C10
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
  }
  materials: {
    Material__2100478577: THREE.MeshBasicMaterial
    Material__2100478581: THREE.MeshBasicMaterial
    Material__2100478583: THREE.MeshBasicMaterial
    Material__2100478584: THREE.MeshBasicMaterial
    Material__2100478585: THREE.MeshBasicMaterial
    Material__2100478586: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/floorplan.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Material__2100478577} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Material__2100478577} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material__2100478577} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material__2100478577} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Material__2100478577} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Material__2100478577} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Material__2100478577} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Material__2100478577} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Material__2100478577} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Material__2100478577} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Material__2100478577} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Material__2100478581} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Material__2100478583} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Material__2100478584} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Material__2100478585} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Material__2100478585} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Material__2100478585} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Material__2100478585} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Material__2100478585} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Material__2100478585} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Material__2100478586} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Material__2100478586} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Material__2100478586} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Material__2100478586} />
      </group>
    </group>
  )
}

useGLTF.preload('/floorplan.glb')
