/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/furniture/gaming_chair.glb 
Author: Connor.Boyle (https://sketchfab.com/Connor.Boyle)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/gaming-chair-78bbf0c67a2a481fa8e476a616d6e178
Title: Gaming Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gaming_chair.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials.standardSurface1} position={[0.22, 0, 55.441]} />
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.standardSurface1} position={[0, 0, 32.467]} />
            <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.standardSurface1} position={[0, -0.439, 30.984]} scale={1.138} />
            <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.standardSurface1} position={[0, 0, 32.467]} />
            <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.standardSurface1} position={[0, 0, 32.467]} />
            <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.standardSurface1} />
            <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.standardSurface1} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/gaming_chair.glb')
